### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by dvic**
Fix warnings as of ~1.2.0-rc2~ 1.2.0

### CODE REVIEW

**Comment by dvic** [comment]
There is still one warning left, but this looks like a compiler issue if I'm not mistaken?

```
❯ gleam build
Downloading packages
 Downloaded 2 packages in 0.02s
  Compiling gleam_stdlib
  Compiling gleeunit
  Compiling gleam_erlang
/Users/dvic/Development/gleam_erlang/build/dev/erlang/gleam_erlang/_gleam_artefacts/gleam@erlang@process_test.erl:442:39: Warning: type variable 'GGA' is only used once (is unbound)
%  442| -spec try_call_timeout_test() -> {ok, GGA} |
%     |                                       ^

   Compiled in 0.78s
```

**Comment by lpil** [comment]
What version is that on @dvic ?

**Comment by dvic** [comment]
> What version is that on @dvic ?

1.2.0

**Comment by dvic** [comment]
I think I see what's going on: if I add `Nil` as the return value to the test in question then the warning goes away:

```gleam
pub fn try_call_timeout_test() {
  let parent_subject = process.new_subject()

  process.start(linked: True, running: fn() {
    // Send the call subject to the parent
    let child_subject = process.new_subject()
    process.send(parent_subject, child_subject)
    // Wait for the subject to be called
    let assert Ok(_) = process.receive(child_subject, 50)
    // Never reply
    process.sleep(100)
  })

  let assert Ok(call_subject) = process.receive(parent_subject, 50)

  // Call the child process over the subject
  let assert Error(process.CallTimeout) =
    process.try_call(call_subject, fn(x) { x }, 10)
  Nil
}
```

So the function is returning 
image

hence the warning, it should use `term()` in the typespec I guess?

**Comment by lpil** [comment]
Thank you. What version of OTP? I'm surprised we're seeing this only now.

**Comment by dvic** [comment]
> Thank you. What version of OTP? I'm surprised we're seeing this only now.

26.2.5, I just tried it with `25.3.2.2` and I see no warnings.

**Comment by dvic** [comment]
Looks like this was indeed intentionally fixed on OTP 26 https://github.com/erlang/otp/issues/6915

**Comment by lpil** [comment]
So if I'm reading this right it is now invalid to have a type parameter that is only used right. Does that match your understanding?

**Comment by dvic** [comment]
> So if I'm reading this right it is now invalid to have a type parameter that is only used right. Does that match your understanding?

Yes, that’s what I also make of it.

**Comment by lpil** [comment]
OK I think this requires a compiler fix. Could you open an issue in the compiler repo with that link, I think we need to replace single type variables with `term()`.

**Comment by dvic** [comment]
@lpil this one got closed by accident because of #3247, that PR only fixed the unbound types issue. This PR also fixed some regular warnings (unnecessary asserts)

**Pull request closed without merging**
