### PR TITLE
Add _env suffix to os functions related to env vars

### PR DESCRIPTION
**Pull request by michallepicki**
There was a suggestion to expand this module with more functionality, e.g. a binding to Erlang's `:os.type()`.

### CODE REVIEW

**Comment by lpil** [comment]
Closes https://github.com/gleam-lang/erlang/issues/9

Would you mind also updating the changelog?

**Comment by michallepicki** [comment]
@lpil Done!

**Review by lpil — APPROVED** [review]
Thank you

**Comment by J3RN** [comment]
Ah, of course! The `_env` suffixes became necessary once the module was renamed from `env` to `os` :facepalm:

**Pull request merged**
